import type { NextPage } from 'next';
import Head from 'next/head';
import { TextInput } from '@labxd/gust';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='fixed w-full h-full flex item-center justify-center flex-col px-4'>
        <TextInput label='label' placeholder='0.00' prefix='$' />
        <TextInput label='label' placeholder='0.00' />
        <TextInput label='label' />
      </main>
    </div>
  );
};

export default Home;
